Add `pow` method
redpanda-data/benthos pull request #14
Opened 2024-06-04 12:49 UTC by mfamador

Add the `pow` method that returns the number raised to a specified exponent.

Ex.:

``` coffee
root.new_value = this.value.pow(2)

# In:  {"value":2}
# Out: {"new_value":4}

# In:  {"value":5}
# Out: {"new_value":25}
``` 

```coffee
root.new_value = this.value * 10.pow(-2)

# In:  {"value":2}
# Out: {"new_value":0.02}
```

2024-06-07 16:40 UTC, Jeffail commented
@mfamador can you move this into the `pure` package. I'm hoping to eventually have all bloblang methods and functions outside of the query stuff.

2024-06-08 12:19 UTC, mfamador commented
I moved it to `pure`. Thanks

2024-06-10 09:49 UTC, Jeffail requested changes

2024-06-10 09:49 UTC, Jeffail commented on internal/impl/pure/bloblang_numbers.go
> +		func(args *bloblang.ParsedParams) (bloblang.Method, error) {
You can do `bloblang.Float64Method(func(input float64) ...` here instead and remove the `getFloat64` function: https://pkg.go.dev/github.com/redpanda-data/benthos/v4@v4.28.1/public/bloblang#Float64Method

2024-06-10 10:50 UTC, mfamador commented on internal/impl/pure/bloblang_numbers.go
> +		func(args *bloblang.ParsedParams) (bloblang.Method, error) {
Chenged, thanks.

2024-06-10 13:20 UTC, merged