add suport for masking
redpanda-data/benthos pull request #19
Opened 2024-06-06 09:06 UTC by pixie79

Adds support to bloblang for basic masking using either a fixed length mask, or partial left / right mask.
Allows to chose the masking character.

2024-06-06 09:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/redpanda-data/benthos?pullRequest=19) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/redpanda-data/benthos?pullRequest=19) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/redpanda-data/benthos?pullRequest=19) it.</sub>

2024-06-12 19:26 UTC, Jeffail requested changes
Hey @pixie79, implementation looks good overall, a few changes needed and then we're gravy.

2024-06-12 19:26 UTC, Jeffail commented on internal/impl/pure/bloblang_mask.go
> +			Param(bloblang.NewInt64Param("mask_count").Description("the number of characters that will not be masked on the left or right hand side, in the case of a all mask, it is the number of mask charact
I would name this just `count`.

2024-06-12 19:26 UTC, Jeffail commented on internal/impl/pure/bloblang_mask.go
> +			Param(bloblang.NewStringParam("mask_char").Description("the character used for masking, default is *").Optional().Default("*")).
Same here, just `char`.

2024-06-12 19:26 UTC, Jeffail commented on internal/impl/pure/bloblang_mask.go
> +					`{"values":{"animal":"cat","fur":["orange","fluffy"],"noise":"meow"}}`,
It looks as though this example is for a different method, and needs updating. But I do like the presence of `meow`, so maybe we can keep that somewhere in the new example.

2024-06-12 19:26 UTC, Jeffail commented on internal/impl/pure/bloblang_mask.go
> +	println("using maskChar: ", maskChar)
```suggestion
```

2024-06-12 19:26 UTC, Jeffail commented on internal/impl/pure/bloblang_mask.go
> +			maskCount, _ := args.GetOptionalInt64("mask_count")
These errors ought to be checked, just a simple return on error is good enough.

2024-06-12 20:44 UTC, pixie79 commented on internal/impl/pure/bloblang_mask.go
> +			Param(bloblang.NewInt64Param("mask_count").Description("the number of characters that will not be masked on the left or right hand side, in the case of a all mask, it is the number of mask charact
Updated

2024-06-12 20:44 UTC, pixie79 commented on internal/impl/pure/bloblang_mask.go
> +			Param(bloblang.NewStringParam("mask_char").Description("the character used for masking, default is *").Optional().Default("*")).
Updated

2024-06-12 20:45 UTC, pixie79 commented on internal/impl/pure/bloblang_mask.go
> +					`{"values":{"animal":"cat","fur":["orange","fluffy"],"noise":"meow"}}`,
lol yup forgot to update that one, done now

2024-06-12 20:45 UTC, pixie79 commented on internal/impl/pure/bloblang_mask.go
> +	println("using maskChar: ", maskChar)
Removed the debug line

2024-06-12 20:45 UTC, pixie79 commented on internal/impl/pure/bloblang_mask.go
> +			maskCount, _ := args.GetOptionalInt64("mask_count")
Added more error handling to return the errors

2024-06-13 06:37 UTC, pixie79 commented
@Jeffail I have made the updates but for some reason and I can't tell why my tests are now failing when I run:
go test internal/impl/pure/bloblang_mask_test.go

I note however that the tests for bloblang_string are also now failing for the same reason?
go test internal/impl/pure/bloblang_string_test.go

Has something else changed? - happy to fix if you can give me a clue

2024-06-13 12:16 UTC, closed without merging